CONTRIBUTORS.md, JavaScript/README.md, JavaScript/package.json, JavaScript/public/index.html, JavaScript/src/App.js, JavaScript/src/index.js, JavaScript/src/styles.css
added recommender based app (ReactJS)
=> Added Recommendation app

amstrongnumber.cpp
created a c++ program to detect 3 digit amstrong number.
=> amstrongnumber.cpp

Java/Account.java, Java/oldMan.java
=> Added OOPS Programs in java

JavaScript/Fun-with-triangles/README.md, JavaScript/Fun-with-triangles/angles.html, JavaScript/Fun-with-triangles/angles.js, JavaScript/Fun-with-triangles/area.html, JavaScript/Fun-with-triangles/area.js, JavaScript/Fun-with-triangles/hypotenuse.html, JavaScript/Fun-with-triangles/index.html, JavaScript/Fun-with-triangles/quiz.html, JavaScript/Fun-with-triangles/quiz.js, JavaScript/Fun-with-triangles/styles.css, README.md
Added a javascript code and updated the readme.md
=> Added fun-with-triangles

CONTRIBUTORS.md, Java/NQueens.java
added NQueens.java & updated CONTRIBUTORS.md
=> add NQueens.java

CPP/ArrayStack.cpp, CPP/LinkedListStack.cpp
Hey, I have added stack data structure both array and linked list implementation in CPP folder.
#11
=> Added Stack DS

CONTRIBUTORS.md, CPP/bubblesort.cpp
I have added bubble sort algorithm in CPP folder.
Review the changes and please merge.
Thanks!!
=> added bubble sort algorithm

JavaScript/Javascript CSS Clock/index.html
An analogue clock built using javascript and css.
=> Javascript/Css Clock

CPP/2darray.cpp
I added 2D-array. Taking values from user and printing them as well printing reverse.
=> 2d array printing

JavaScript/calculator/README.md, JavaScript/calculator/calculator.html, JavaScript/calculator/calculator.js
Basic Javascript project - Calculator
=> calculator project added

C/GOL.c, C/README.md
Added a C program based on John Conway's game of life
=> Added Game of life

linkedlist.c
LinkedListImplementation in C LANGUAGE
=> LinkedListImplementation in C #hacktoberfest

CONTRIBUTORS.md, Python/Tower of Hanoi/Tower_of_Hanoi.py
Also Added name in Contributor list
=> Tower of Hanoi Python Implementation

Java/GenericSort.java
A Generic method that can perform the sorting of any type of data.
=> add GenericSort.java

Java/Calculator.java
This is a calculator made using java.
This program will allow the user to follow the following operations:
1)Add ('+')
2)Subtract('-')
3)Multiply('*')
4)Modulo or Remainder ('%')
5)Divide('/')
NOTE: this program is made using while loop. So this program will run until the user enters 'x' or "X".
=> Add calculator using java

CPP/specific pair in the matrix.cpp
=> new c++ file added

JavaScript/Datastructure/Sorting.js
Bubble Sort
Selection Sort
Insertion Sort
Merge Sort
Quick Sort
Heap Sort
=> Sorting Algorithm

CPP/Rope cutting problem.cpp
Added Rope cutting problem.cpp program
=> Added Rope cutting problem.cpp program

JavaScript/TowerOfHanoi.js
=> Tower Of Hanoi

CPP/Linklist_insert_at_begin.cpp, CPP/Linklist_insert_at_end.cpp
Added insertion of node at beginning of link list
=> Added Linklist_insert_at_begin.cpp

Java/guess-number-game.java
This is a game where the user has to guess a value between 0-100 Computer will generate a random number between 0-100. If your guess matches you will win
=> guess-number-game.java

Java/BinarySearch.java
Binary Search for array in ascending order and descending order in java
=> Added binary search algorithm in java

Python/Searching Algorithms/Binary_Search.py, Python/Searching Algorithms/Linear_Search.py
Searching Algorithms Added in Newly Created Folder name - **Sorting Algorithms**
=> Linear Search and Binary Search Added under Python/Sorting Algorithms

Java/Fibonacci.java
This program will print **Fibonacci series.**
Fibonacci series is a series of numbers where the number is the **sum of the preceding two numbers**
for example : if the user inputs **5**  then the output will be **0 1 1 2 3** i.e upto 5 digits.
The **first digit 0 i**s printed **before** entering the while loop.
**WORKING of while loop:** 
while loop will run until the value of count becomes **n-1**.                                                        
-->**counter = b** (we can't assign "b's" value to "a" directly so we need to use counter)
-->**b=b + a** (as Fibonacci is based on the sum of preceding two numbers)
-->**a** = counter (now we can assign b's value to 'a' with the help of counter)
-->**count++**     (incrementing count by 1)
-->**System.out.print(a + " ")**        (now …
=> Fibonacci series using java

HTML/Snake game/readme.md, HTML/Snake game/snake.html
I've added html folder under which i have created snake game using html.
=> HTML section

C/tower_of_hanoi.c
Hello as assigned I have submitted the c program to solve the Tower of Hanoi. Do let me know if there are any problems.
Thank you
=> add c program for tower of hanoi

C/fibonacci_number.c
This is a c program to find the nth term of Fibonacci series using recursive functions.
=>  add c program for fibonacci series
